"use client";
import { Analytics } from "@vercel/analytics/react";
import { Poppins } from "next/font/google";
import { store } from "./redux/store";
import { Provider } from "react-redux";
import "./globals.css";
import { GoogleOAuthProvider } from "@react-oauth/google";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <GoogleOAuthProvider clientId="801064546104-59ceuepf5flhunktpf3f5876og9jlqrg.apps.googleusercontent.com">
      <html className={`${poppins.variable}`}>
        <Provider store={store}>
          <body>{children}</body>
          <Analytics />
        </Provider>
      </html>
    </GoogleOAuthProvider>
  );
}
